---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  tslint:
    enabled: true
    config: tslint.json
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- dist/*
- node_modules/**/*
- test/**/*