language: node_js


node_js: "stable"


cache:
  directories:
    - node_modules


dist: trusty
sudo: required


addons:
  github-token: $GITHUB_TOKEN
  code_climate:
    repo_token: 
      secure: $TEST_REPORTER_ID


before_script:
 #install chrome
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 

script:
  - npm run lint


after_success:
  - git clone https://github.com/rhnylyukh/learnwithmentor-web.git
  - cd learnwithmentor-web/
  - git config user.name $USER
  - git config user.email "rhnylyukh@gmail.com"
  - git config user.password $PASS
  - git checkout test
  - git checkout master
  - git merge test
  - git push origin master
  

after_script:
 - npm install -g codeclimate-test-reporter
 - cat coverage/lcov.info | codeclimate-test-reporter
 - codeclimate-test-reporter < ./coverage/lcov.info
 

notifications:
  slack: lv319net:D2CDMCaLF2nn5ppAbx7PWtz8
